name: translator
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.1
  http: ^0.12.2
  dartx: ^0.5.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.10.4
  freezed: ^0.12.7
  json_serializable: ^3.5.1
